install.packages('data.table',repos = 'https://mirrors.tongji.edu.cn/CRAN/')
install.packages('devtools',repos = 'https://mirrors.tongji.edu.cn/CRAN/')
install.packages('Rcpp',repos = 'https://mirrors.tongji.edu.cn/CRAN/')
devtools::install_github('lchiffon/REmap')
devtools::install_github('badbye/baidumap')
